---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedge-ecds-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubedge-ecds-operator
  template:
    metadata:
      labels:
        name: kubedge-ecds-operator
    spec:
      serviceAccountName: kubedge-ecds-operator
      containers:
        - name: kubedge-ecds-operator
          # Replace this with the built image name
          image: kubedge1/kubedge-ecds-operator:v0.2.0
          command:
          - /usr/local/bin/kubedge-ecds-operator
          imagePullPolicy: "IfNotPresent"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubedge-ecds-operator"
      nodeSelector:
        czZone: enabled
